"""Expose job introspection and foreground debugging compatibility helpers."""

# The imports below deliberately preserve the complete historical module surface.
# ruff cannot infer names exported by the whitespace-based __all__ assembly.

import json
import shutil
import tempfile
import time
from collections.abc import Callable, Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any

from .._util import read_json, timestamp_seconds
from ..errors import WorkflowError, WorkspaceCorruptionError
from ..journal import read_record
from ..manager import TaskManager
from ..manifests import read_maintenance_lock
from ..models import (
    CORE_PROFILE,
    CORE_STATE_KINDS,
    DEFAULT_LEASE_SECONDS,
    QUIESCENT_KINDS,
    STATE_KINDS,
    TERMINAL_KINDS,
    JobDefinition,
    Marker,
    normalize_placement,
    validate_step,
)
from ..workspace import MarkerFault, Workspace
from ._debug import (
    DEBUG_EXIT_FAILED,
    DEBUG_EXIT_SUCCEEDED,
    DEBUG_EXIT_UNFINISHED,
    DebugOutcome,
    ScopedWorkspace,
    _drive,
    _drive_children,
    _exit_code,
    _frame_summary,
    _print_line,
    _pump,
    _stage_payload_with_step,
    _Tail,
    debug_job,
)
from ._diagnosis import (
    JOB_DIAGNOSIS_FORMAT,
    BudgetStatus,
    Check,
    ClaimRequirements,
    Diagnosis,
    ManagerRecord,
    _breadcrumb_check,
    _budget_checks,
    _continue_checks,
    _describe_child,
    _Diagnosing,
    _label_sequence,
    _label_set,
    _maintenance_check,
    _manager_checks,
    _owner_checks,
    _placement_covered,
    _profile_check,
    _requirement_checks,
    budget_status,
    claim_requirements,
    explain_job,
    manager_refusals,
    observe_join,
    read_managers,
)
from ._reading import (
    _HISTORY_READ_DEADLINE_SECONDS,
    JOB_HISTORY_FORMAT,
    JOB_LIST_FORMAT,
    JobListPage,
    JobSelectorResolver,
    _attempt_control,
    _job_of,
    _optional_float,
    _optional_int,
    _optional_string,
    _state_of,
    _workdir_relative,
    count_markers,
    iter_markers,
    job_frames,
    list_jobs,
    read_error_breadcrumb,
    resolve_job,
    resolve_job_selector,
    resolve_job_selectors,
    selector_is_path,
    selector_uses_remote_path,
)
from ._rendering import (
    JOB_REPORT_FORMAT,
    _pair,
    describe_job,
    render_frames,
    render_job,
    render_rows,
)

__all__ = [
    "CORE_PROFILE",
    "CORE_STATE_KINDS",
    "DEBUG_EXIT_FAILED",
    "DEBUG_EXIT_SUCCEEDED",
    "DEBUG_EXIT_UNFINISHED",
    "DEFAULT_LEASE_SECONDS",
    "JOB_DIAGNOSIS_FORMAT",
    "JOB_HISTORY_FORMAT",
    "JOB_LIST_FORMAT",
    "JOB_REPORT_FORMAT",
    "QUIESCENT_KINDS",
    "STATE_KINDS",
    "TERMINAL_KINDS",
    "_HISTORY_READ_DEADLINE_SECONDS",
    "Any",
    "BudgetStatus",
    "Callable",
    "Check",
    "ClaimRequirements",
    "DebugOutcome",
    "Diagnosis",
    "Iterable",
    "Iterator",
    "JobDefinition",
    "JobListPage",
    "JobSelectorResolver",
    "ManagerRecord",
    "Mapping",
    "Marker",
    "MarkerFault",
    "Path",
    "PurePosixPath",
    "ScopedWorkspace",
    "Sequence",
    "TaskManager",
    "WorkflowError",
    "Workspace",
    "WorkspaceCorruptionError",
    "_Diagnosing",
    "_Tail",
    "_attempt_control",
    "_breadcrumb_check",
    "_budget_checks",
    "_continue_checks",
    "_describe_child",
    "_drive",
    "_drive_children",
    "_exit_code",
    "_frame_summary",
    "_job_of",
    "_label_sequence",
    "_label_set",
    "_maintenance_check",
    "_manager_checks",
    "_optional_float",
    "_optional_int",
    "_optional_string",
    "_owner_checks",
    "_pair",
    "_placement_covered",
    "_print_line",
    "_profile_check",
    "_pump",
    "_requirement_checks",
    "_stage_payload_with_step",
    "_state_of",
    "_workdir_relative",
    "budget_status",
    "claim_requirements",
    "count_markers",
    "dataclass",
    "debug_job",
    "describe_job",
    "explain_job",
    "field",
    "iter_markers",
    "job_frames",
    "json",
    "list_jobs",
    "manager_refusals",
    "normalize_placement",
    "observe_join",
    "read_error_breadcrumb",
    "read_json",
    "read_maintenance_lock",
    "read_managers",
    "read_record",
    "render_frames",
    "render_job",
    "render_rows",
    "resolve_job",
    "resolve_job_selector",
    "resolve_job_selectors",
    "selector_is_path",
    "selector_uses_remote_path",
    "shutil",
    "tempfile",
    "time",
    "timestamp_seconds",
    "validate_step",
]  # pyright: ignore[reportUnsupportedDunderAll]
