"""Packaged dispatcher for manager launcher bundles."""

import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import uuid
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

BATCH_DIRECTORY = ".httk-workspace/batch"
BATCH_DIRECTIVES = (
    ("slurm.account", "--account"),
    ("slurm.partition", "--partition"),
    ("slurm.time_limit", "--time"),
    ("slurm.nodes", "--nodes"),
    ("slurm.cpus_per_task", "--cpus-per-task"),
    ("slurm.reservation", "--reservation"),
)
SUPPORTED_KINDS = ("slurm",)
_CONTROL_CHARACTER = re.compile(r"[\x00-\x1f\x7f]")
_SUBMITTED_JOB = re.compile(r"Submitted batch job (\d+)")


def _result(operation: str, **values: object) -> None:
    print(
        json.dumps(
            {
                "format": "httk-manager-launcher-result",
                "format_version": 2,
                "operation": operation,
                "ok": True,
                **values,
            },
            sort_keys=True,
            separators=(",", ":"),
        )
    )


def _refusal(operation: str, message: str) -> None:
    print(
        json.dumps(
            {
                "error": message,
                "format": "httk-manager-launcher-result",
                "format_version": 2,
                "operation": operation,
                "ok": False,
            },
            sort_keys=True,
            separators=(",", ":"),
        )
    )


def _metadata(request: Mapping[str, object]) -> dict[str, Any]:
    value = request.get("launcher_dir")
    if not isinstance(value, str) or not value:
        raise ValueError("launcher request must carry launcher_dir")
    path = Path(value).expanduser() / "launcher.json"
    document = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise ValueError(f"launcher JSON must be an object: {path}")
    return document


def _text(settings: Mapping[str, object], key: str) -> str | None:
    value = settings.get(key)
    if value is None or isinstance(value, bool) or not isinstance(value, (str, int, float)):
        return None
    text = str(value).strip()
    return text or None


def _batch_value(key: str, value: str) -> str:
    if _CONTROL_CHARACTER.search(value):
        raise ValueError(f"launcher setting {key} must not contain control characters")
    return value


def _request_argv(request: Mapping[str, object]) -> list[str]:
    value = request.get("argv")
    if not isinstance(value, list) or not value or not all(isinstance(item, str) for item in value):
        raise ValueError("start argv must be a nonempty string array")
    return list(value)


def _workspace(request: Mapping[str, object]) -> str:
    value = request.get("workspace")
    if not isinstance(value, str) or not value:
        raise ValueError("start needs a workspace path in the request")
    return value


def _count(request: Mapping[str, object]) -> int:
    value = request.get("count", 1)
    if isinstance(value, bool) or not isinstance(value, int) or value < 1:
        raise ValueError("start count must be a positive integer")
    return value


def _settings(request: Mapping[str, object]) -> dict[str, object]:
    value = request.get("settings", {})
    if not isinstance(value, Mapping):
        raise ValueError("start settings must be an object")
    return dict(value)


def _batch_script(argv: Sequence[str], *, settings: Mapping[str, object], workspace: str, directory: str) -> str:
    """Compose the Slurm script submitted for one manager."""

    lines = ["#!/bin/bash -l", "# Generated by the httk workflow slurm launcher.", "#SBATCH --job-name=httk-manager"]
    for key, directive in BATCH_DIRECTIVES:
        value = _text(settings, key)
        if value is not None:
            lines.append(f"#SBATCH {directive}={_batch_value(key, value)}")
    lines += [
        f"#SBATCH --chdir={_batch_value('workspace', workspace)}",
        f"#SBATCH --output={_batch_value('workspace', directory)}/manager-%j.out",
        f"#SBATCH --error={_batch_value('workspace', directory)}/manager-%j.err",
        "",
        "set -e",
    ]
    prelude = _text(settings, "environment.prelude")
    if prelude:
        lines.append(prelude)
    lines += [f"exec {shlex.join(argv)}", ""]
    return "\n".join(lines)


def _start_slurm(request: Mapping[str, object]) -> None:
    workspace = _workspace(request)
    settings = _settings(request)
    count = _count(request)
    directory = Path(workspace) / BATCH_DIRECTORY
    directory.mkdir(parents=True, exist_ok=True)
    script_path = directory / f"manager-{uuid.uuid4().hex}.sbatch"
    script_path.write_text(
        _batch_script(_request_argv(request), settings=settings, workspace=workspace, directory=str(directory)),
        encoding="utf-8",
    )
    os.chmod(script_path, 0o700)
    job_ids: list[str] = []
    for _ in range(count):
        completed = subprocess.run(
            ["sbatch", str(script_path)], cwd=workspace, text=True, capture_output=True, check=False
        )
        if completed.returncode != 0:
            raise RuntimeError(completed.stderr.strip() or f"sbatch exited with status {completed.returncode}")
        match = _SUBMITTED_JOB.search(completed.stdout)
        if match is None:
            raise RuntimeError(
                completed.stderr.strip() or f"sbatch did not report a submitted job: {completed.stdout.strip()}"
            )
        job_ids.append(match.group(1))
    _result("start", kind="slurm", count=count, job_ids=job_ids, script=str(script_path))


def main(argv: list[str] | None = None) -> int:
    """Dispatch one launcher request file.

    :param argv: Dispatcher arguments, or process arguments when omitted.
    :return: Zero after writing a launcher result document.
    """

    arguments = sys.argv[1:] if argv is None else argv
    if len(arguments) != 1:
        print("launcher dispatcher expects one REQUEST.json path", file=sys.stderr)
        return 2
    try:
        request = json.loads(Path(arguments[0]).read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        print(f"launcher dispatcher: {exc}", file=sys.stderr)
        return 2
    operation = request.get("operation") if isinstance(request, dict) else None
    if not isinstance(operation, str) or operation not in {"check", "start"}:
        print("launcher request must carry operation check or start", file=sys.stderr)
        return 2
    try:
        document = _metadata(request)
        kind = document.get("kind")
        if kind not in SUPPORTED_KINDS:
            _refusal(
                operation,
                f"launcher kind {kind!r} is not implemented; the packaged launchers support {', '.join(SUPPORTED_KINDS)} - refusing",
            )
            return 0
        if operation == "check":
            binaries = document.get("required_binaries", [])
            if not isinstance(binaries, Sequence) or isinstance(binaries, (str, bytes)):
                raise ValueError("required_binaries must be an array")
            missing = [binary for binary in binaries if not isinstance(binary, str) or not shutil.which(binary)]
            if missing:
                raise RuntimeError(
                    f"required launcher binary is unavailable: {', '.join(str(item) for item in missing)}"
                )
            _result("check", kind=kind)
        else:
            _start_slurm(request)
    except (OSError, RuntimeError, ValueError, KeyError, json.JSONDecodeError) as exc:
        _refusal(operation, f"launcher {operation}: {exc}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
