"""Small, dependency-free VASP runner helpers for native v2 workflows.

This is an independent, data-oriented interface rather than a port of the
historic ``VASP_*`` Python or shell APIs. Historical authorship is documented
in ``v1_runtime/NOTICE``.
"""

import bz2
import gzip
import lzma
import math
import os
import re
import tempfile
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class PoscarHeader:
    """The VASP-5 header information needed by execution helpers."""

    comment: str
    scale: float
    lattice: tuple[tuple[float, float, float], ...]
    species: tuple[str, ...]
    counts: tuple[int, ...]


def read_poscar_header(path: str | os.PathLike[str] = "POSCAR") -> PoscarHeader:
    """Read a VASP-5 POSCAR header without interpreting site coordinates."""

    lines = Path(path).read_text(encoding="utf-8").splitlines()
    if len(lines) < 7:
        raise ValueError("POSCAR has fewer than seven header lines")
    try:
        scale = float(lines[1].split()[0])
        raw_lattice = [tuple(float(item) for item in lines[index].split()) for index in range(2, 5)]
        counts = tuple(int(item) for item in lines[6].split())
    except (IndexError, ValueError) as exc:
        raise ValueError("POSCAR contains an invalid scale, lattice, or count line") from exc
    if len(raw_lattice) != 3 or any(len(row) != 3 for row in raw_lattice):
        raise ValueError("POSCAR lattice must contain three three-component rows")
    lattice = (
        (raw_lattice[0][0], raw_lattice[0][1], raw_lattice[0][2]),
        (raw_lattice[1][0], raw_lattice[1][1], raw_lattice[1][2]),
        (raw_lattice[2][0], raw_lattice[2][1], raw_lattice[2][2]),
    )
    species = tuple(lines[5].split())
    if not species or len(species) != len(counts) or any(value < 0 for value in counts):
        raise ValueError("POSCAR requires matching VASP-5 species and nonnegative counts")
    return PoscarHeader(lines[0], scale, lattice, species, counts)


def suggested_magnetic_moments(path: str | os.PathLike[str] = "POSCAR") -> str:
    """Return the explicit comment override or a five-per-atom default."""

    header = read_poscar_header(path)
    override = re.search(r"\[MAGMOM=([^\]]+)\]", header.comment)
    if override is not None:
        return override.group(1)
    return " ".join(f"{count}*5" for count in header.counts)


def _cross(left: Sequence[float], right: Sequence[float]) -> tuple[float, float, float]:
    return (
        left[1] * right[2] - left[2] * right[1],
        left[2] * right[0] - left[0] * right[2],
        left[0] * right[1] - left[1] * right[0],
    )


def _dot(left: Sequence[float], right: Sequence[float]) -> float:
    return sum(a * b for a, b in zip(left, right, strict=True))


def automatic_kpoint_grid(
    density: float,
    *,
    poscar: str | os.PathLike[str] = "POSCAR",
    minimum: int = 3,
    equal: bool = False,
    bump: int = 0,
) -> tuple[int, int, int]:
    """Calculate a reciprocal-length automatic grid."""

    if density <= 0 or minimum < 1 or bump < 0:
        raise ValueError("density must be positive; minimum must be positive; bump cannot be negative")
    header = read_poscar_header(poscar)
    first, second, third = header.lattice
    determinant = _dot(first, _cross(second, third))
    if abs(determinant) < 1e-12:
        raise ValueError("POSCAR lattice is singular")
    scale = header.scale
    if scale < 0:
        scale = (-scale / abs(determinant)) ** (1.0 / 3.0)
    if scale == 0:
        raise ValueError("POSCAR scale cannot be zero")
    reciprocal = (
        _cross(second, third),
        _cross(third, first),
        _cross(first, second),
    )
    lengths = tuple(math.sqrt(_dot(row, row)) / abs(determinant * scale) for row in reciprocal)
    values = tuple(max(minimum, math.ceil(density * length + 0.5) + bump) for length in lengths)
    grid = (values[0], values[1], values[2])
    if equal:
        largest = max(grid)
        return largest, largest, largest
    return grid


def write_automatic_kpoints(
    grid: Sequence[int],
    path: str | os.PathLike[str] = "KPOINTS",
    *,
    centering: str = "Gamma",
) -> Path:
    """Write a standard automatic KPOINTS file."""

    values = tuple(grid)
    if len(values) != 3 or any(isinstance(value, bool) or value < 1 for value in values):
        raise ValueError("grid must contain three positive integers")
    if centering not in {"Gamma", "Monkhorst-Pack"}:
        raise ValueError("centering must be 'Gamma' or 'Monkhorst-Pack'")
    destination = Path(path)
    destination.write_text(
        "Automatic mesh generated by httk\n" "0\n" f"{centering}\n" f"{values[0]} {values[1]} {values[2]}\n" "0 0 0\n",
        encoding="utf-8",
    )
    return destination


def read_incar(path: str | os.PathLike[str] = "INCAR") -> dict[str, str]:
    """Read the last value of each simple INCAR assignment."""

    result: dict[str, str] = {}
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        content = re.split(r"[#!]", line, maxsplit=1)[0]
        for statement in content.split(";"):
            name, separator, value = statement.partition("=")
            key = name.strip().upper()
            if separator and key:
                result[key] = value.strip()
    return result


def update_incar(
    values: Mapping[str, object],
    path: str | os.PathLike[str] = "INCAR",
) -> Path:
    """Atomically replace selected INCAR tags while preserving other lines."""

    destination = Path(path)
    normalized = {str(name).strip().upper(): str(value) for name, value in values.items()}
    if not normalized or any(not name or re.fullmatch(r"[A-Z][A-Z0-9_]*", name) is None for name in normalized):
        raise ValueError("INCAR updates require valid nonempty tag names")
    kept: list[str] = []
    pattern = re.compile(r"^\s*([A-Za-z][A-Za-z0-9_]*)\s*=")
    for line in destination.read_text(encoding="utf-8").splitlines():
        match = pattern.match(line)
        if match is None or match.group(1).upper() not in normalized:
            kept.append(line)
    kept.extend(f"{name} = {value}" for name, value in normalized.items())
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{destination.name}.", dir=destination.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write("\n".join(kept) + "\n")
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)
    return destination


def _read_potential(path: Path) -> bytes:
    if path.name == "POTCAR":
        return path.read_bytes()
    if path.name == "POTCAR.gz":
        return gzip.decompress(path.read_bytes())
    if path.name == "POTCAR.bz2":
        return bz2.decompress(path.read_bytes())
    if path.name in {"POTCAR.xz", "POTCAR.lzma"}:
        return lzma.decompress(path.read_bytes())
    raise ValueError(f"unsupported pseudopotential compression: {path}")


def assemble_potcar(
    library: str | os.PathLike[str],
    *,
    poscar: str | os.PathLike[str] = "POSCAR",
    output: str | os.PathLike[str] = "POTCAR",
    suffix_preference: Iterable[str] = ("_3", "_2", "_d", "_sv", "_pv", "", "_h", "_s"),
) -> Path:
    """Assemble POTCAR from explicit species and a configurable suffix policy."""

    root = Path(library).expanduser().resolve()
    header = read_poscar_header(poscar)
    suffixes = tuple(suffix_preference)
    pieces: list[bytes] = []
    for species in header.species:
        found: Path | None = None
        for suffix in suffixes:
            directory = root / f"{species}{suffix}"
            for filename in ("POTCAR", "POTCAR.gz", "POTCAR.bz2", "POTCAR.xz", "POTCAR.lzma"):
                candidate = directory / filename
                if candidate.is_file():
                    found = candidate
                    break
            if found is not None:
                break
        if found is None:
            raise FileNotFoundError(f"no pseudopotential found for species {species!r} below {root}")
        pieces.append(_read_potential(found))
    destination = Path(output)
    destination.write_bytes(b"".join(pieces))
    return destination


def last_oszicar_energy(path: str | os.PathLike[str] = "OSZICAR") -> float | None:
    """Return the final ``E0`` value, or ``None`` when it is absent."""

    found: float | None = None
    pattern = re.compile(r"\bE0=\s*([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[Ee][-+]?\d+)?)")
    for line in Path(path).read_text(encoding="utf-8", errors="replace").splitlines():
        match = pattern.search(line)
        if match is not None:
            found = float(match.group(1))
    return found


def contcar_to_poscar(
    contcar: str | os.PathLike[str] = "CONTCAR",
    *,
    reference: str | os.PathLike[str] = "POSCAR",
    output: str | os.PathLike[str] = "POSCAR",
) -> Path:
    """Replace CONTCAR's comment with the reference POSCAR comment."""

    reference_lines = Path(reference).read_text(encoding="utf-8").splitlines(keepends=True)
    lines = Path(contcar).read_text(encoding="utf-8").splitlines(keepends=True)
    if not reference_lines or not lines:
        raise ValueError("CONTCAR and reference POSCAR must both be nonempty")
    destination = Path(output)
    destination.write_text(reference_lines[0].rstrip("\r\n") + "\n" + "".join(lines[1:]), encoding="utf-8")
    return destination
